services:

  spring_boot:
    build:
      context: .
      dockerfile: Dockerfile
    image: kimeunsur/birthday:latest
    container_name: birthday_dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
