spring.application.name=birthday
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2
kakao.redirect-uri=http://localhost:8080/api/users/login/oauth/kakao
kakao.key.client-id=${KAKAO_CLIENT_ID}
custom.jwt.secretKey=${JWT_SECRET_KEY}


# Swagger UI 경로
springdoc.swagger-ui.path=/swagger.html
# Swagger UI 정렬 설정
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
# OpenAPI 스펙 경로
springdoc.api-docs.path=/api-docs
# 기본 Media Type 설정
springdoc.default-consumes-media-type=application/json;charset=UTF-8
springdoc.default-produces-media-type=application/json;charset=UTF-8