name: Deploy Spring Boot to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate application.yml from secret
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > ./src/main/resources/application.yml

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Check JAR output
        run: ls -al build/libs

      - name: Copy application.yml to root for Docker build
        run: cp ./src/main/resources/application.yml ./application.yml

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: |
            build/libs/*.jar
            Dockerfile
            application.yml
            deploy.sh
          target: "~/birthday-hansang"

      - name: Run deploy script on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/birthday-hansang
            chmod +x deploy.sh
            ./deploy.sh
